Sprint 2
user14052020/middle.messenger.praktikum.yandex pull request #2
Opened 2022-09-07 05:31 UTC by user14052020

Приветствую!
Подключён TypeScript. Добавлен компонентный подход. Добавлен класс для работы с запросами. Добавлены ESLint, Stylelint.

2022-09-07 19:51 UTC, podlovchenko requested changes
Привет) Есть несколько замечаний
1. Много мест, где не добавлена типизация, а также есть ошибки в добавленной, попробуй выполнить команду `npx tsc --noEmit`
2. Валидация данных не  совсем корректная, имя и фамилия могут быть больше 2 символов
3. Было бы здорово привести в порядок код, поправить отступы, пробелы, убрать закомментированный код, ошибки EOF, в этом может помочь https://prettier.io/docs/en/install.html

2022-09-07 19:51 UTC, podlovchenko commented on .eslintignore
> +/node_modules
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-09-07 19:51 UTC, podlovchenko commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.36.1",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-09-07 19:51 UTC, podlovchenko commented on src/blocks/atorization_registration_input_block/index.ts
> +  atorizationRegistrationInput: string;
authorization?

2022-09-07 19:51 UTC, podlovchenko commented on src/blocks/menu/index.ts
> +    super('nav', props);
Можно было бы сделать props необязательным в конструкторе Block, чтобы не прокидывать пустой объект

2022-09-07 19:51 UTC, podlovchenko commented on src/blocks/profile_change_info_row/profile_change_info_row.css
> +form.profil-forma .inp-holder input {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-09-07 19:51 UTC, podlovchenko commented on src/blocks/profile_row/profile_row.css
> +.prof-table.d-flex .prof-table-row .prof-table-col.prof-table-col-left p {
Точно нужна такая вложенность классов? Такое сложно поддерживать, лучше завести отдельные классы

2022-09-07 19:51 UTC, podlovchenko commented on src/components/input/index.ts
> +    }else if(this.element?.id === 'passwordval'){
switch case?

2022-09-07 19:51 UTC, podlovchenko commented on src/components/input/index.ts
> +    let nameRGEX = /^[A-ZА-ЯЁ][ёa-zа-я-]$/;
Только 2 символа проходят по такой регулярке

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/Block.ts
> +class Block {
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/Block.ts
> +  // }
Закомментированный код лучше не оставлять в проекте

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/Block.ts
> +  _getChildrenAndProps(childrenAndProps: any) {
Не хватает модификатора private для приватных методов

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/EventBus.ts
> +  on(event, callback) {
Было бы отлично добавить типы для аргументов функции

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/EventBus.ts
> +  private readonly listeners: Record<string, Array<() => void>> = {};
Листенеры могут принимать аргументы, тип () => void не совсем подходит

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/httptransport.ts
> +};
Можно использовать enum

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/httptransport.ts
> +		get = (url, options = {}) => {
Не хватает типизации

2022-09-07 19:51 UTC, podlovchenko commented on src/utils/httptransport.ts
> +			  });
Отступы поехали

2022-09-08 11:00 UTC, user14052020 commented on .eslintignore
> +/node_modules
исправлено

2022-09-08 11:00 UTC, user14052020 commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.36.1",
исправлено

2022-09-08 11:00 UTC, user14052020 commented on src/blocks/atorization_registration_input_block/index.ts
> +  atorizationRegistrationInput: string;
исправлено

2022-09-08 11:02 UTC, user14052020 commented on src/blocks/menu/index.ts
> +    super('nav', props);
исправлено

2022-09-08 11:19 UTC, user14052020 commented on src/components/input/index.ts
> +    }else if(this.element?.id === 'passwordval'){
тогда потребуется переписывать всю функцию под swich case так как если просто заменить каждый if на case то получаю ошибку SyntaxError: Cannot declare a let variable twice: 'errorPage'. Можно ли пропустить данное замечание так как планируется писать роутинг в следующем скрипте?

2022-09-08 11:25 UTC, user14052020 commented on src/components/input/index.ts
> +    let nameRGEX = /^[A-ZА-ЯЁ][ёa-zа-я-]$/;
исправлено

2022-09-08 11:26 UTC, user14052020 commented on src/utils/Block.ts
> +  // }
исправлено

2022-09-08 11:32 UTC, user14052020 commented on src/utils/httptransport.ts
> +};
исправлено

2022-09-08 11:35 UTC, user14052020 commented on src/utils/httptransport.ts
> +			  });
исправлено

2022-09-09 09:38 UTC, user14052020 commented on src/blocks/profile_change_info_row/profile_change_info_row.css
> +form.profil-forma .inp-holder input {
исправлено

2022-09-09 09:39 UTC, user14052020 commented on src/blocks/profile_row/profile_row.css
> +.prof-table.d-flex .prof-table-row .prof-table-col.prof-table-col-left p {
исправлено

2022-09-10 09:43 UTC, user14052020 commented on src/utils/EventBus.ts
> +  on(event, callback) {
исправлено

2022-09-10 09:43 UTC, user14052020 commented on src/utils/EventBus.ts
> +  private readonly listeners: Record<string, Array<() => void>> = {};
исправлено

2022-09-10 09:43 UTC, user14052020 commented on src/utils/httptransport.ts
> +		get = (url, options = {}) => {
исправлено

2022-09-10 10:01 UTC, user14052020 commented on src/utils/Block.ts
> +  _getChildrenAndProps(childrenAndProps: any) {
исправлено

2022-09-10 15:00 UTC, podlovchenko approved these changes
Работу принимаю)

2022-09-10 15:00 UTC, podlovchenko commented on src/components/button/index.ts
>          for (var key of formData.keys()) {
var устарело, сейчас используется let

2022-09-10 15:00 UTC, podlovchenko commented on src/utils/httptransport.ts
> +enum METHODS {
enum обычно именуется в PascalCase

2022-09-10 15:00 UTC, podlovchenko commented on src/utils/httptransport.ts
> +	get = (url:string, options: Options) => {
Метод здесь уже не нужно пробрасывать, можно использовать дженерик Omit
```suggestion
	get = (url:string, options: Omit<Options, 'method'>) => {
```

2022-09-11 04:18 UTC, user14052020 commented on src/components/button/index.ts
>          for (var key of formData.keys()) {
исправлено

2022-09-11 04:21 UTC, user14052020 commented on src/utils/Block.ts
> +class Block {
исправлено

2022-09-11 04:21 UTC, user14052020 commented on src/utils/httptransport.ts
> +enum METHODS {
исправлено

2022-09-11 04:35 UTC, merged